export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";


